on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP_ADDRESS_EC2_PAGOS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
              sudo yum install -y nodejs npm git
        
      - name: Create Working Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP_ADDRESS_EC2_PAGOS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
              if [ -d "/opt/WorkingDirectoryPagos" ]; then
              sudo rm -rf /opt/WorkingDirectoryPagos
              fi
              sudo mkdir /opt/WorkingDirectoryPagos
              cd /opt/WorkingDirectoryPagos
      
      - name: Clone Repository T2-Devops
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP_ADDRESS_EC2_PAGOS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
            sudo git clone https://${{ secrets.PAT}}@github.com/FedeMerayo/DevOps-T2.git /opt/WorkingDirectoryPagos

      - name: Install NPM Packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP_ADDRESS_EC2_PAGOS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
              sudo npm install express
              sudo npm install -g pm2
      
      - name: Start Node Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP_ADDRESS_EC2_PAGOS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
            pm2 start -f /opt/WorkingDirectoryPagos/app.js

         
      - name: Check Status
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP_ADDRESS_EC2_PAGOS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
            if pm2 list | grep -q 'app'; then
            echo "La aplicaci칩n est치 corriendo."
            else
            echo "La aplicaci칩n no est치 corriendo."
            fi
