name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag t2-devops-k6:latest   
    
    - name: Push the Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/t2-devops-k6:latest
